### ISSUE TITLE
Forgot selection operator in rbga?

### ISSUE THREAD

**Issue by ballings** [egonw/genalg#1]
Egon,

I found an important bug in your rbga function in the genalg package.

It seems that you forgot to apply the selection operator. You simply sort the chromosomes and randomly select two parents. Instead you should give a chromosome with a higher fitness a higher probability to be selected. If you run rbga without elitism the fitness does not improve over generations (because you forget the selection step). I adapted your function and ran it on the same problem and it fixed the problem.

This line:

parentIDs = sample(1:popSize, 2)

Should be replaced by these two lines:

parentProb = dnorm(1:popSize, mean = 0, sd = (popSize/3))
parentIDs = sample(1:popSize, 2, prob = parentProb)

Michel

**Comment by schwidom** [comment]
I would not recommend that this way. 
There may be a lot of different possible genalg implementations.
This is not really a bug.
If you are using elite chromosomes too often, then it is harder to leave local minima.
What you reach is, that a local minimum is faster found.
I would recomend to provide the parentProb-Vector as an Parameter. If it is NULL, it must not be used. And if it is set, it may not be recalculated every step (it is a constant vector).

Frank

**Comment by schwidom** [comment]
issue is closed by providing parentProb as an rbga\* parameter
